[build]
  publish = "."  # Mappen där din HTML-fil finns
  functions = "netlify/functions" # Mappen där dina serverlösa funktioner finns

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "node-fetch"]
